---
abstract: "Perl extension to OpenSSL's X509 API."
author:
  - 'Dan Sully'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-OpenSSL-X509
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.005
resources:
  bugtracker: https://github.com/dsully/perl-crypt-openssl-x509/issues
  homepage: https://github.com/dsully/perl-crypt-openssl-x509
  license: http://dev.perl.org/licenses/
  repository: https://github.com/dsully/perl-crypt-openssl-x509
version: 1.804
