
name: macos-latest

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  perl:
    name: macos-latest

    runs-on: macOS-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          persist-credentials: false
      - name: install dependencies
        run: |
          brew install openssl@3
      - name: Install Perl dependencies with cpanm
        uses: perl-actions/install-with-cpanm@10d60f00b4073f484fc29d45bfbe2f776397ab3d # v1.7
        with:
          cpanfile: "cpanfile"
          args: "--with-configure"
          sudo: false
      - name: perl -V
        run: perl -V

      - name: Run Tests
        env:
          OPENSSL_PREFIX: /opt/homebrew/opt/openssl@3
        run: |
          export PKG_CONFIG_PATH="$OPENSSL_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
          export LDFLAGS="-L$OPENSSL_PREFIX/lib"
          export CPPFLAGS="-I$OPENSSL_PREFIX/include"
          export DYLD_LIBRARY_PATH="$OPENSSL_PREFIX/lib:$DYLD_LIBRARY_PATH"
          perl Makefile.PL
          make
          make test
