
name: macos-latest

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: macOS-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4.2.0
      - name: install dependencies
        run: |
          brew install openssl@1.1
      - name: uses install-with-cpanm
        uses: perl-actions/install-with-cpanm@v1.7
        with:
          cpanfile: "cpanfile"
          args: "--with-configure"
          sudo: false
      - name: perl -V
        run: perl -V

      - name: Run Tests
        run: |
          perl Makefile.PL
          make
          make test
