
name: macos-latest

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  perl:
    name: macos-latest

    runs-on: macOS-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: install dependencies
        run: |
          brew install openssl@3
      - name: Install Perl dependencies with cpanm
        uses: perl-actions/install-with-cpanm@8ec40bce95c287169e8c13551e5e49d0185ce955 # v2.2
        with:
          cpanfile: "cpanfile"
          args: "--with-configure"
          sudo: false
      - name: perl -V
        run: perl -V

      - name: Run Tests
        env:
          OPENSSL_PREFIX: /opt/homebrew/opt/openssl@3
        run: |
          export PKG_CONFIG_PATH="$OPENSSL_PREFIX/lib/pkgconfig:$PKG_CONFIG_PATH"
          export LDFLAGS="-L$OPENSSL_PREFIX/lib"
          export CPPFLAGS="-I$OPENSSL_PREFIX/include"
          export DYLD_LIBRARY_PATH="$OPENSSL_PREFIX/lib:$DYLD_LIBRARY_PATH"
          perl Makefile.PL
          make
          make test
